>Gene.1::SOAP_k35_scaffold1::g.1::m.1 type:5prime_partial len:176 gc:Tetrahymena SOAP_k35_scaffold1:2-529(+)
DVFILNKLQNVQCQQINLKQFQKNGQQTILSVCQNNNRAHMASSSKFQICKITSHVVLGLKGNLKKRLQTSYMPLQLIGTAQAVCSPANLLSHTEPWIPQSPTSYIYEESPNPCQTTQLKILQVHKTLIGLKSTQVGSFLQCHCVFKKYTSSKGKKQICTTCLVLLQTLQLGISV*
>Gene.2::SOAP_k35_scaffold1::g.2::m.2 type:complete len:151 gc:Tetrahymena SOAP_k35_scaffold1:424-876(+)
MSLCLQEIHFQQGQKTDLYHLFGFATNTSVGHFCLNQTGFQQMKETFCQSVEIFQQKSFLCMTCKNKHQHYLYSQLVILCLTQINLDPNYHLSTYLTLKQAQCGVKEKKNIWRLHPNKLPLKQTQNTTTVLSAQFLTLIVTVTIHSLQND*
>Gene.3::SOAP_k35_scaffold1::g.3::m.3 type:complete len:150 gc:Tetrahymena SOAP_k35_scaffold1:603-1052(+)
MHDLQKQTSTLLVFLTSNLVFNTNKPRPKLPSLYIPHIKVSIMWGKREKKHLAVAPEQTTVKTNTEHYHCSFSLIPHIDSHCYNTFPLKRLKSGFFKLFQXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXS*
>Gene.4::SOAP_k35_scaffold1::g.4::m.4 type:complete len:128 gc:Tetrahymena SOAP_k35_scaffold1:1593-1976(+)
MKTKNKDSNQASSYFSNTLQCCVYIPNRKSLVFRSIAQNKMCIAVSYTIQKNNPFEEQQCDHKRHPLLLIFFCFLCQWFGRHQRPTLSFQYIGRELDFPISVSSFLPSLHQPLRIDLPVCAEVRVLD*
>Gene.5::SOAP_k35_scaffold1::g.5::m.5 type:complete len:118 gc:Tetrahymena SOAP_k35_scaffold1:1468-1115(-)
MLDYEFKNGVPQQASQLNPTCLQHRLPVKKCERHQLMLPLYVFLCAEICWTYTCCIQKEQPRCFFHFFHCSFFNHIFILVVXXXXXXXXXXXXXXXXXXXXXXXXXXXRHYEAFQRL*
>Gene.6::SOAP_k35_scaffold1::g.6::m.6 type:5prime_partial len:108 gc:Tetrahymena SOAP_k35_scaffold1:1-324(+)
GRFYFKQIIKCTMLINQSKTVLKEWVANNFERLLEQQQGTYGIQFQVLDLQNHLTCGSGTKREFKKAAVDQLHATPTNWHCSGSVFSCQPIEPHRTMDSPITHFLHI*
>Gene.7::SOAP_k35_scaffold1::g.7::m.7 type:complete len:107 gc:Tetrahymena SOAP_k35_scaffold1:1137-817(-)
MRLFNVFDPKSSNKYSRKALTRKDSQIGFNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXIGIVQRSRTSVVLEGMYCNSDYQCEELS*
>Gene.8::SOAP_k35_scaffold1::g.8::m.8 type:complete len:103 gc:Tetrahymena SOAP_k35_scaffold1:706-398(-)
MQRDGSLGLGLFVLNTRLLVKNTSSVDVCFCKSCIEKTFTEIFLQTDKMFLSFVKNRFNSNRNAQLKCLQQNQTSGTNLFFTLAGSVFLKDTMTLQKGPHLC*
>Gene.9::SOAP_k35_scaffold2::g.9::m.9 type:5prime_partial len:106 gc:Tetrahymena SOAP_k35_scaffold2:1-318(+)
FILDDVNPRVLSVSSWTMSTQDVLVFHPGLCQPKRSQCFILNDVNPRVLSASSWMISTHAFLMFLPRQCQLKMTQCFILDDINPGVLCDQSWLMSSHEFLVLYPG*
